# Nombre del flujo de trabajo
name: Entrenamiento de Modelo de Seguros

# Disparador: Se ejecuta cada vez que subes código a la rama 'main'
on:
  push:
    branches: [ main ]

# Tareas a ejecutar
jobs:
  build:
    # La máquina virtual que usará GitHub (Ubuntu es la estándar)
    runs-on: ubuntu-latest

    steps:
    # 1. Clona tu repositorio en la máquina virtual
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    # 2. Configura Python en la máquina virtual
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Usamos la misma versión que tú

    # 3. Instala las dependencias de tu proyecto
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Ejecuta el script de entrenamiento
    - name: Ejecutar script de entrenamiento
      run: python python_train.py